update CI, read specific vars in npzread
fhs/NPZ.jl pull request #39
Opened 2020-11-10 11:18 UTC by jishnub

Firstly this PR adds the option to read specific variables in `npzread` instead of all the variables.

Secondly it adds docstrings to `npzread` and `npzwrite`. It also adds a documentation generation workflow.

Thirdly it updates the CI to github actions from travis, and updates Tagbot as [suggested here](https://discourse.julialang.org/t/ann-required-updates-to-tagbot-yml/49249). Tbh I'm not totally sure if this is done correctly.

2020-11-10 11:37 UTC, jishnub commented
The readme badge needs to be updated, perhaps this can be done after merging.

2020-11-11 22:39 UTC, fhs requested changes
Thanks!

I'm don't know how to the documentation deployment works. From a brief look at the docs, I guess it pushes the generated documentation to this repo?

I would've preferred a separate PR for the `npzread` changes, but it's fine.

2020-11-12 06:26 UTC, jishnub commented on .github/workflows/ci.yml
> +          - '1'
My bad, I will update this. Any particular reason to test on 1.1 though, given that it is not supported anymore?

2020-11-12 06:27 UTC, jishnub commented on .github/workflows/ci.yml
> +          - ubuntu-latest
I will add it, my bad, I had copied the template from PkgCompiler

2020-11-12 06:28 UTC, jishnub commented on .github/workflows/ci.yml
> +          - '1'
Along the same lines, testing on 1.0 should be enough to not require a separate test on 0.7, as 1.0 is essentially 0.7 without deprecation messages

2020-11-12 06:46 UTC, jishnub commented
yes I realize now that separate PRs would have been a better idea.

The documentation workflow pushes commits to the `gh-pages` branch. It might be necessary to select this branch as the source of github pages from settings. Although I've only used travis for this, and there might be [issues with using github actions for this](https://github.com/JuliaDocs/Documenter.jl/issues/1177). Reading through the issue it seems that [using an SSH deploy key ](https://github.com/JuliaDocs/Documenter.jl/issues/1177#issuecomment-555034592)should get around this, so I'm adding this for the time being.

2020-11-12 06:51 UTC, jishnub commented on docs/Project.toml
> +Documenter = "0.25"
I've added this now

2020-11-12 06:51 UTC, jishnub commented on src/NPZ.jl
> +Read an variable or a collection of variables from `filename`.
Fixed

2020-11-12 06:51 UTC, jishnub commented on .github/workflows/ci.yml
> +          - ubuntu-latest
Fixed

2020-11-12 18:00 UTC, fhs commented on .github/workflows/ci.yml
> +          - '1'
Good to know. I'll change them to currently supported versions, which I think are 1.5 and 1.0.

2020-11-12 18:02 UTC, fhs approved these changes
Thanks!

2020-11-12 18:07 UTC, merged